### ISSUE TITLE
Remake the navigation bar and logic

### ISSUE THREAD

**Issue by ThomasPFMuller** [WanderWise-Inc/app#142]
To be synchronized with the Figma, redo the navigation bar and logic.
- Should remove Search screen (itinerary search functionnality already provided in overview and liked screen)
- Should add a "create a new itinerary screen"
- Update navigation between screens
- If time available, add different navigation methods to change how backstack keeps page history

-> Making HomeNavigationTest work took a long time as I had to convert to using mockk

**Comment by 276746** [comment]
PR #135
