### ISSUE TITLE
ISSUE#205 Create Itinerary UI: Preview Itinerary screen

### ISSUE THREAD

**Issue by 276746** [WanderWise-Inc/app#207]
This screen should present the user with a complete preview of their itinerary with the waypoints and the path calculated to wander them.

![Image](https://github.com/WanderWise-Inc/app/assets/100191653/d3c43697-9c35-40a1-88ab-e7e65cd1eb5a)

**Comment by 276746** [comment]
PR #199

**Comment by gunnm0** [comment]
took some time to convince people of the implementation I wanted.
