### ISSUE TITLE
As a developper, i would like to have a code that is well commented so that other developpers can understand it

### ISSUE THREAD

**Issue by engjellismaili** [WanderWise-Inc/app#317]

**Comment by engjellismaili** [comment]
PR #315 contributed to it

**Comment by 276746** [comment]
PR https://github.com/WanderWise-Inc/app/pull/306
PR https://github.com/WanderWise-Inc/app/pull/307
PR https://github.com/WanderWise-Inc/app/pull/308
PR https://github.com/WanderWise-Inc/app/pull/309
PR https://github.com/WanderWise-Inc/app/pull/310
PR #319 
PR #316 
PR #313 
PR #312 
PR #311
