### ISSUE TITLE
Setup skeleton + infrastructure for Maps interaction

### ISSUE THREAD

**Issue by ethangraham2001** [WanderWise-Inc/app#8]
- Write Model classes `Location` and `Itinerary`
- write view model class(es) for interaction with firebase
- do some tests on UI to see what we can achieve with maps UI
- Deliver a first working composable to Thomas who is working on setting up navigation

**Comment by imaneb942** [comment]
| | Infos|
|---|---|
|Estimate Time| h |
|Time Spent| h|
